/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductPaginationModel } from '../../models/product-pagination-model';
import { ProductQuery } from '../../models/product-query';

export interface ProductsQueryPagePost$Xml$Params {
  authorization?: string;
      body: ProductQuery
}

export function productsQueryPagePost$Xml(http: HttpClient, rootUrl: string, params: ProductsQueryPagePost$Xml$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductPaginationModel>> {
  const rb = new RequestBuilder(rootUrl, productsQueryPagePost$Xml.PATH, 'post');
  if (params) {
    rb.header('authorization', params.authorization, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/xml', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductPaginationModel>;
    })
  );
}

productsQueryPagePost$Xml.PATH = '/products/queryPage';
