/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductGroupPaginationModel } from '../../models/product-group-pagination-model';
import { ProductGroupQuery } from '../../models/product-group-query';

export interface ProductGroupsQueryPagePost$Json$Params {
  authorization?: string;
      body: ProductGroupQuery
}

export function productGroupsQueryPagePost$Json(http: HttpClient, rootUrl: string, params: ProductGroupsQueryPagePost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductGroupPaginationModel>> {
  const rb = new RequestBuilder(rootUrl, productGroupsQueryPagePost$Json.PATH, 'post');
  if (params) {
    rb.header('authorization', params.authorization, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductGroupPaginationModel>;
    })
  );
}

productGroupsQueryPagePost$Json.PATH = '/product-groups/queryPage';
