/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductGroup } from '../../models/product-group';

export interface ProductGroupsPost$Xml$Params {
  authorization?: string;
      body: ProductGroup
}

export function productGroupsPost$Xml(http: HttpClient, rootUrl: string, params: ProductGroupsPost$Xml$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductGroup>> {
  const rb = new RequestBuilder(rootUrl, productGroupsPost$Xml.PATH, 'post');
  if (params) {
    rb.header('authorization', params.authorization, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/xml', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductGroup>;
    })
  );
}

productGroupsPost$Xml.PATH = '/product-groups/';
