/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomerGroup } from '../../models/customer-group';

export interface CustomerGroupsPost$Json$Params {
  authorization?: string;
      body: CustomerGroup
}

export function customerGroupsPost$Json(http: HttpClient, rootUrl: string, params: CustomerGroupsPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerGroup>> {
  const rb = new RequestBuilder(rootUrl, customerGroupsPost$Json.PATH, 'post');
  if (params) {
    rb.header('authorization', params.authorization, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomerGroup>;
    })
  );
}

customerGroupsPost$Json.PATH = '/customer-groups/';
