/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomerGroup } from '../../models/customer-group';

export interface CustomerGroupsFindAllGet$Json$Params {
  authorization?: string;
}

export function customerGroupsFindAllGet$Json(http: HttpClient, rootUrl: string, params?: CustomerGroupsFindAllGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CustomerGroup>>> {
  const rb = new RequestBuilder(rootUrl, customerGroupsFindAllGet$Json.PATH, 'get');
  if (params) {
    rb.header('authorization', params.authorization, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CustomerGroup>>;
    })
  );
}

customerGroupsFindAllGet$Json.PATH = '/customer-groups/findAll';
