/* tslint:disable */
/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CustomerQuery {
    filter: {
        name?: string;
        surname?: string;
        phone?: string;
    };
    page?: number;
    size?: number;
}
