/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Customer {
  address?: string;
  changed_by?: string;
  created_at?: string;
  id?: number;
  name?: string;
  phone?: string;
  surname?: string;
  updated_at?: string;
}
