/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {Customer} from "./customer";

export interface CustomerPaginationModel {
    currentPage?: number;
    totalItems?: number;
    totalPages?: number;
    tutorials?: Array<Customer>;
}
