/* tslint:disable */
/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CustomerGroupQuery {
    filter?: {
        name?: string;
    };
    page?: number;
    size?: number;
}
