/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {CustomerGroup} from "./customer-group";

export interface CustomerGroupPaginationModel {
  currentPage?: number;
  totalItems?: number;
  totalPages?: number;
  tutorials?: Array<CustomerGroup>;
}
