/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Order {
  changed_by?: string;
  created_at?: string;
  id?: number;
  name?: string;
  orderDetails?: Array<Array<any>>;
  updated_at?: string;
}
