/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderPaginationModel {
  currentPage?: number;
  totalItems?: number;
  totalPages?: number;
  tutorials?: Array<Array<any>>;
}
