/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {ProductGroup} from "./product-group";

export interface ProductGroupPaginationModel {
  currentPage?: number;
  totalItems?: number;
  totalPages?: number;
  tutorials?: Array<ProductGroup>;
}
