/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Product {
  changed_by?: string;
  created_at?: string;
  id?: number;
  max_discount?: string;
  name?: string;
  price?: string;
  product_group_id?: string;
  updated_at?: string;
}
