/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductGroup {
  changed_by?: string;
  created_at?: string;
  id?: number;
  name?: string;
  updated_at?: string;
}
