/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {Product} from "./product";

export interface ProductPaginationModel {
  currentPage?: number;
  totalItems?: number;
  totalPages?: number;
  tutorials?: Array<Product>;
}
