/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductGroupQuery {
  filter?: {
'name'?: string;
};
  page?: number;
  size?: number;
}
