/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface User {
  changed_by?: string;
  createdAt?: Date;
  id?: number;
  name?: string;
  password?: string;
  surname?: string;
  updatedAt?: Date;
  username?: string;
}
