/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserQueryModel {
  filter?: {
'name'?: string;
'surname'?: string;
'username'?: string;
};
  page?: number;
  size?: number;
}
