/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {User} from "./user";

export interface UserPaginationModel {
  currentPage?: number;
  totalItems?: number;
  totalPages?: number;
  tutorials?: Array<User>;
}
